Dev
Sergei-Iurevich/blog pull request #1
Opened 2021-04-08 19:22 UTC by Sergei-Iurevich

2021-04-09 17:57 UTC, AntiHero requested changes

2021-04-09 17:57 UTC, AntiHero commented on src/html/parts/head.html
> +<!DOCTYPE html>
добавить индивидуальный html/head для каждой странички

2021-04-09 17:57 UTC, AntiHero commented on src/html/parts/head.html
> +    <meta charset="UTF-8" />
+ meta viewport https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

2021-04-09 17:57 UTC, AntiHero commented on src/style/scss/style.scss
> +  font-size: 100%;
не нужно

2021-04-09 17:57 UTC, AntiHero commented on src/style/scss/style.scss
> +        display: inline-block;
`display: block`

2021-04-28 13:55 UTC, Sergei-Iurevich commented on src/html/parts/head.html
> +<!DOCTYPE html>
Поправил.

2021-04-28 13:56 UTC, Sergei-Iurevich commented on src/html/parts/head.html
> +    <meta charset="UTF-8" />
Добавил

2021-04-28 14:02 UTC, Sergei-Iurevich commented on src/style/scss/style.scss
> +  font-size: 100%;
Убрал

2021-04-28 14:06 UTC, Sergei-Iurevich commented on src/style/scss/style.scss
> +        display: inline-block;
Поправил

2021-04-28 16:00 UTC, AntiHero commented on src/style/scss/style.scss
> +  padding: 10px 10px 10px 10px;
можно просто `padding: 10px;` здесь можешь почитать про сокращения принятые в css https://cssdog.com/css_shortcuts.html

2021-04-30 06:33 UTC, merged